name: Build and Deploy

on:
  workflow_dispatch:
#on:
#  push:
#    branches:
#    - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'v16.19.1'
          cache: 'npm'
        
      - name: Install
        run: npm install

      - name: Build 
        run: |
          npm run build-css
          npm run build

      #- name: Deploy to GitHub Pages
      #  uses: JamesIves/github-pages-deploy-action@v4
      #  with:
      #    branch: deploy
      #    folder: build
      
      # New step to zip the build folder
      - name: Zip Build Artifacts
        run: zip -r build.zip build/

      # New step to upload the zip file as an artifact
      - name: Upload Build Zip To Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-zip
          path: build.zip  
